-- AlterEnum
ALTER TYPE "ExpenseType" ADD VALUE IF NOT EXISTS 'SALARY';
ALTER TYPE "ExpenseType" ADD VALUE IF NOT EXISTS 'SUPPLIES';
ALTER TYPE "ExpenseType" ADD VALUE IF NOT EXISTS 'RENT';
ALTER TYPE "ExpenseType" ADD VALUE IF NOT EXISTS 'SERVICES';
ALTER TYPE "ExpenseType" ADD VALUE IF NOT EXISTS 'MAINTENANCE';

-- AlterTable
ALTER TABLE "expenses" ADD COLUMN IF NOT EXISTS "observations" TEXT;
ALTER TABLE "expenses" ADD COLUMN IF NOT EXISTS "createdBy" TEXT NOT NULL DEFAULT 'system';
